Iterate the pre-check to include an interoperability check
digitalservicebund/digitalcheck-apps pull request #239
Opened 2024-12-16 10:17 UTC by mpanne

- Add questions regarding EU interoperability
- Update pre-check landing and result pages to include information about interoperability
- Add page with general information prior to pre-check questions
- Update content of some pre-check pages

2024-12-20 16:44 UTC, HendrikSchmidt requested changes
Hey, great work! I left a mix of nitpicks and medium proposals, lmk if you need any clarification.

With the possible refactorings and maybe pulling some components out of `ResultPage` (`ReasoningList` first and foremost probably), I am starting to think we might get away without the three files and could still merge `route.tsx` and `ResultPage`. Interested in your thoughts!

2024-12-20 16:44 UTC, HendrikSchmidt commented on packages/dito/app/routes/vorpruefung.ergebnis/ResultPage.tsx
> +  function getReasonListItem(data: {
As this and the next three functions don't access local variables, I would pull them out of `ResultPage` and also simplify them to something like 

```
function getReasonListItem(tuple: QuestionAndAnswer) {
  const classes = classNames("w-28 h-auto", {
    "fill-green-900": tuple.answer === "yes",
    "fill-red-900": tuple.answer === "no",
  });
  const resultType =
    tuple.answer === "no" ? "negativeResult" : "positiveResult";
  const resultHint = tuple.question?.resultHint?.[resultType];
  return (
    <>
      {tuple.answer === "yes" && <ControlPointOutlined className={classes} />}
      {tuple.answer === "no" && <RemoveCircleOutline className={classes} />}
      {tuple.answer === "unsure" && <HelpOutline className={classes} />}
      <span>
        <span>
          {tuple.question?.[resultType]}
          {resultHint && <RichText markdown={resultHint} />}
        </span>
      </span>
    </>
  );
}

function getReasonsList(questions: QuestionAndAnswer[], intro: string) {
  return (
    questions.length !== 0 && (
      <>
        <RichText className="mt-40" markdown={intro} />
        <ul className="ds-stack-16 mt-16">
          {questions
            .toSorted((t1) => (t1.answer === "yes" ? -1 : 1))
            .map((tuple) => (
              <li key={tuple.question.id} className="flex items-start gap-12">
                {getReasonListItem(tuple)}
              </li>
            ))}
        </ul>
      </>
    )
  );
}
``` 
> [!WARNING]
> Not tested!

2024-12-20 16:44 UTC, HendrikSchmidt commented on packages/dito/app/routes/vorpruefung.ergebnis/ResultPage.tsx
> +          <div className="pb-40 border-solid border-0 border-b-2 border-gray-400 last:border-0 last:pb-0">
`border-0` seems unnecessary here

2024-12-20 16:44 UTC, HendrikSchmidt commented on packages/dito/app/routes/vorpruefung.ergebnis/ResultPage.tsx
> +function matchQuestionsAndAnswers(answers: PreCheckAnswers) {
How about the following changes in tandem with the lower comments

```
function getRelevantQuestionsAndAnswers(
  answers: PreCheckAnswers,
  interoperability: boolean,
  sure: boolean,
) {
  return questions
    .filter(
      (q) =>
        !!q.interoperability === interoperability &&
        (answers[q.id] !== "unsure") === sure,
    )
    .map((q) => ({ question: q, answer: answers[q.id] }));
}
```

2024-12-20 16:44 UTC, HendrikSchmidt commented on packages/dito/app/routes/vorpruefung.ergebnis/ResultPage.tsx
> +  const questionsAndAnswers = matchQuestionsAndAnswers(answers);
```
const { reasoningIntro } = preCheck.result;
  const reasoning = [
    {
      intro: reasoningIntro.digital.sure,
      questions: getRelevantQuestionsAndAnswers(answers, false, true),
    },
    {
      intro: reasoningIntro.digital.unsure,
      questions: getRelevantQuestionsAndAnswers(answers, false, false),
    },
    {
      intro: reasoningIntro.interoperability.sure,
      questions: getRelevantQuestionsAndAnswers(answers, true, true),
    },
    {
      intro: reasoningIntro.interoperability.unsure,
      questions: getRelevantQuestionsAndAnswers(answers, true, false),
    },
  ];
```

2024-12-20 16:44 UTC, HendrikSchmidt commented on packages/dito/app/routes/vorpruefung.ergebnis/ResultPage.tsx
> +            {getReasonsList(
With the above changes the following four elements become just this

```
            {reasoning.map(({ intro, questions }) =>
              getReasonsList(questions, intro),
            )}
```

2025-01-07 11:22 UTC, mpanne commented on .github/workflows/test-build-deploy.yml
> -    if: ${{ github.ref == 'refs/heads/main' }}
Yes, that's the whole point of it. To have the PR branches built so that we can use the published images for staging deployment (manually atm). That way we could also test a `dependabot` PR on staging. Whereas I agree that this is more an unwanted side effect than a feature. Do you see a problem with this approach?

2025-01-07 11:23 UTC, mpanne commented on packages/dito/app/components/AccordionItem.tsx
> +    <details
Thank you. To be perfectly honest though: it's stolen from Grundsteuer. ;)

2025-01-07 11:24 UTC, mpanne commented on packages/dito/app/components/AccordionItem.tsx
> +  const [isExpanded, setIsExpanded] = useState(false);
I re-used the Grundsteuer component and did not specifically think about that behavior. What would be the reason to only keep one item open?

2025-01-07 11:26 UTC, mpanne commented on packages/dito/app/components/AccordionItem.tsx
> +  const [isExpanded, setIsExpanded] = useState(false);
I will ask Giang what reasons she sees for either way.

2025-01-07 11:26 UTC, mpanne commented on packages/dito/app/components/AccordionItem.tsx
> +      onToggle={() => setIsExpanded(!isExpanded)}
See comment above

2025-01-07 11:27 UTC, mpanne commented on packages/dito/app/components/AccordionItem.tsx
> +        role="button"
re-used component. I'm unsure myself. Will keep it like that for now, trusting Grundsteuer until I'm proven wrong.

2025-01-07 11:29 UTC, mpanne commented on packages/dito/app/components/AccordionItem.tsx
> +            { "text-blue-800": boldAppearance },
It also changes the font size few lines later.

2025-01-07 11:40 UTC, mpanne commented on packages/dito/app/resources/content.ts
> +- **Digitalisierungspotenziale frühzeitig nutzen:** Wenn Sie frühzeitig Chancen für die Digitalisierung erkennen, optimieren Sie den Regelungstext und sichern Sie sich technisch und rechtlich ab und
Not needed here

2025-01-07 11:40 UTC, mpanne commented on packages/dito/app/resources/content.ts
> +- **EU-Anforderungen identifizieren:** Im Rahmen der Vorprüfung ermitteln Sie, ob grenzüberschreitende Interoperabilität für Ihr Vorhaben relevant ist. Regelungen die  Interoperabilität fördern, ermö
not needed

2025-01-07 11:41 UTC, mpanne commented on packages/dito/app/resources/content.ts
> +- **Rechtliche Grundlage:** Seit Juni 2024 ist es verpflichtend nationale Regelungsvorhaben auf Digitaltauglichkeit zu prüfen. Die Grundlage dafür ist das Onlinezugangsgesetz (OZG) von 2017. Zusätzli
not needed

2025-01-07 11:42 UTC, mpanne commented on packages/dito/app/resources/content.ts
> +Der Digitalcheck gilt für alle Regelungsvorhaben - Gesetze, Verordnungen und Verwaltungsvorschriften. Es fallen sowohl neue Vorhaben, als auch für Änderungen an bestehenden Regelungen darunter.`,
Good catch

2025-01-07 11:42 UTC, mpanne commented on packages/dito/app/resources/content.ts
> +        content: `Digitalbezug im Kontext der Umsetzung bedeutet, dass ein Prozess zumindest teilweise durch ein IT-System abgebildet  wird. Beispiele sind:
Good catch

2025-01-07 12:06 UTC, mpanne commented on packages/dito/app/routes/vorpruefung._index.tsx
> +          <div className="ds-stack-16 mb-40">
The `ButtonContainer` below should not be included which is why this is an additional `div`

2025-01-07 12:08 UTC, mpanne commented on packages/dito/app/routes/vorpruefung._index.tsx
> +        <Background backgroundColor="blue">
Does not work due to the padding the container has. The background should only be the area inside without the padding.

2025-01-07 12:10 UTC, mpanne commented on packages/dito/app/routes/vorpruefung._index.tsx
> +            <div className="md:pl-32 ds-stack-8 gap-20 md:w-1/3">
The first `div` is the container for image and text whereas the nested container is only for the images. Merging would not work. Using the root `Container` for paddings does not work since there is the `Background` in between which cannot be removed (see comment above).

2025-01-07 12:12 UTC, mpanne commented on packages/dito/app/routes/vorpruefung.ergebnis/TResult.tsx
> +export type TResult = {
Matter of taste I guess? I like having separate files to keep classes with business logic "clean". But I see that this is not consistent because we don't do that anywhere else. I will move it to the `vorpruefung.ergebnis/route.tsx`.

2025-01-07 12:13 UTC, mpanne commented on packages/dito/app/routes/vorpruefung.ergebnis/TResult.tsx
> +export type TResult = {
Ah no, this does not work since I cannot export the type and enum in the same file as I export a component. Where would you place such a type?

2025-01-07 12:15 UTC, mpanne commented on packages/dito/app/routes/vorpruefung.ergebnis/route.tsx
> +    const email = formData.get("email");
Yes, we will get rid of the download action. What can be done simpler in that case? (see current implementation)

2025-01-07 12:17 UTC, mpanne commented on packages/dito/app/routes/vorpruefung.ergebnis/route.tsx
> +    const additionalRecipient = email !== null ? `,${email as string}` : "";
Good catch. Done

2025-01-07 12:18 UTC, mpanne commented on packages/dito/app/routes/vorpruefung.ergebnis/route.tsx
> +    const additionalRecipient = email !== null ? `,${email as string}` : "";
Even if I think that `formData` will not include an `undefined` or empty string `""` value.

2025-01-07 12:28 UTC, mpanne commented on packages/dito/app/resources/content.ts
> +              <br />
Considered. Thanks

2025-01-07 12:29 UTC, mpanne commented on packages/dito/app/components/AccordionItem.tsx
> +  const [isExpanded, setIsExpanded] = useState(false);
According to our design it should be possible to have multiple items open at the same time so I will leave it like that.

2025-01-07 12:30 UTC, mpanne commented on packages/dito/app/routes/vorpruefung.ergebnis/ResultPage.tsx
I agree. This will be something for a post release refactoring since it will take some more time.

2025-01-07 12:32 UTC, mpanne commented on packages/dito/app/routes/vorpruefung.ergebnis/ResultPage.tsx
> +  function getReasonListItem(data: {
Refactored. Thank you for the inspiration. I used some of your code of this and the following comments.

2025-01-07 12:32 UTC, mpanne commented on packages/dito/app/routes/vorpruefung.ergebnis/ResultPage.tsx
> +function matchQuestionsAndAnswers(answers: PreCheckAnswers) {
refactored, see comment above

2025-01-07 12:33 UTC, mpanne commented on packages/dito/app/routes/vorpruefung.ergebnis/ResultPage.tsx
> +  const questionsAndAnswers = matchQuestionsAndAnswers(answers);
refactored

2025-01-07 12:33 UTC, mpanne commented on packages/dito/app/routes/vorpruefung.ergebnis/ResultPage.tsx
> +            {getReasonsList(
refactored

2025-01-07 12:42 UTC, mpanne commented on packages/dito/app/routes/vorpruefung.ergebnis/route.tsx
> +function getResult(answers: PreCheckAnswers): TResult {
I kiss your eyes. 😗 👁️
I used your code and inlined the last function. Makes it much shorter and better readable!

2025-01-07 13:26 UTC, HendrikSchmidt commented on .github/workflows/test-build-deploy.yml
> -    if: ${{ github.ref == 'refs/heads/main' }}
No :) I just overlooked that there still is a separate deployment step afterwards

2025-01-07 13:29 UTC, HendrikSchmidt commented on packages/dito/app/components/AccordionItem.tsx
> +  const [isExpanded, setIsExpanded] = useState(false);
I still wonder whether we need react state for this or if the native HTML element already captures that behavior?

2025-01-07 13:32 UTC, HendrikSchmidt commented on packages/dito/app/components/AccordionItem.tsx
> +        role="button"
Seems to be the default role already: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary#:~:text=Because%20the%20%3Csummary%3E%20element%20has%20a%20default%20role%20of%20button%20(which%20strips%20all%20roles%20from%20child%20elements)%2C%20this%20example%20will%20not%20work%20for%20users%20of%20assistive%20technologies%20such%20as%20screen%20readers. So could be dropped?

2025-01-07 13:45 UTC, HendrikSchmidt commented on packages/dito/app/routes/vorpruefung.ergebnis/TResult.tsx
> +export type TResult = {
I don't have a clear answer. I would maybe move `ResultType` to `resolveResultContent.ts` and `TResult` (probably with a different name as we haven't been using the `T`-prefix so far) to the `route.tsx`? I also noticed that you sometimes aren't importing the type as `impot type ...`, which probably doesn't have direct ramifications in our context, but could make the intent clearer to the reader :)

2025-01-07 13:53 UTC, HendrikSchmidt commented on packages/dito/app/routes/vorpruefung.ergebnis/route.tsx
> +    const email = formData.get("email");
I guess we could get rid of the `_action` entirely, other than that, I don't see a lot of room for improvements at the moment.

2025-01-07 14:19 UTC, HendrikSchmidt requested changes
Some smaller changes could be done, but looking good!

2025-01-07 14:19 UTC, HendrikSchmidt commented on packages/dito/app/routes/vorpruefung.ergebnis/ResultPage.tsx
> +  function getIconForReason(reason: Reason) {
Consider pulling out of component, as it doesn't access variables from the scope.

2025-01-07 15:33 UTC, mpanne commented on packages/dito/app/routes/vorpruefung.ergebnis/TResult.tsx
> +export type TResult = {
- I would like to keep those two together. I will move both to `resolveResultContent` for now. 
- The `T`-prefix was actually inspired from `TQuestion` which [you introduced at some point](https://github.com/digitalservicebund/digitalcheck-apps/commit/aead7b0b#diff-932acdae669e0ba3b522a9e2a7f7c05feb352fc8e1b04d9e1fe518f89bc73df7). 😉 
- Good point with the imports. Actually I always let my IDE handle all the inputs and never look at them. But that might not be the best choice since I also messed up several imports by adding them with e.g. `../../` and not by their alias. I will try to find a way to clean that up but probably after merge.

2025-01-07 16:04 UTC, mpanne commented on packages/dito/app/routes/vorpruefung.ergebnis/route.tsx
> +    const email = formData.get("email");
True. Will do

2025-01-07 16:10 UTC, HendrikSchmidt commented on packages/dito/app/routes/vorpruefung.ergebnis/TResult.tsx
> +export type TResult = {
Shots fired! Disregard what I said :D

2025-01-07 16:12 UTC, mpanne commented on packages/dito/app/routes/vorpruefung.ergebnis/ResultPage.tsx
> +              <>
It doesn't work without it since an element is expected.

2025-01-07 16:24 UTC, HendrikSchmidt commented on packages/dito/app/routes/vorpruefung.ergebnis/ResultPage.tsx
> +              <>
I think you could either do
```
              {resultContent.reasoningList.map(
                ({ intro, reasons }) =>
                  reasons.length > 0 && (
                    <>
                      <RichText className="mt-40 first:mt-0" markdown={intro} />
                      <ul className="ds-stack-16 mt-16">
                        {reasons
                          .toSorted((reason) => (reason.answer === "yes" ? -1 : 1))
                          .map((reason) => getReasonListItem(reason))}
                      </ul>
                    </>
                  ),
              )}
```
or maybe even cleaner
```
              {resultContent.reasoningList
                .filter(({ reasons }) => reasons.length > 0)
                .map(({ intro, reasons }) => (
                  <>
                    <RichText className="mt-40 first:mt-0" markdown={intro} />
                    <ul className="ds-stack-16 mt-16">
                      {reasons
                        .toSorted((reason) =>
                          reason.answer === "yes" ? -1 : 1,
                        )
                        .map((reason) => getReasonListItem(reason))}
                    </ul>
                  </>
                ))}
```

SonarCube also complains about the usage of `sort()` here and advises it should be the newly added `toSorted()` (already replaced in my code). I'm also using `> 0` instead of `!== 0`.

2025-01-07 16:25 UTC, mpanne commented on packages/dito/app/components/AccordionItem.tsx
> +  const [isExpanded, setIsExpanded] = useState(false);
I will check, thanks!

2025-01-07 16:30 UTC, mpanne commented on packages/dito/app/routes/vorpruefung.ergebnis/ResultPage.tsx
> +              <>
Super nice, thanks. Used the second version!

2025-01-07 16:52 UTC, HendrikSchmidt approved these changes

2025-01-08 08:25 UTC, merged

2025-01-09 08:10 UTC, mpanne commented on packages/dito/app/components/AccordionItem.tsx
> +  const [isExpanded, setIsExpanded] = useState(false);
The elements handle accessibility for the expanded/collapsed state already natively indeed.